### ISSUE TITLE
Give this a read please for your issue

### ISSUE THREAD

**Issue by Martii** [HaleShaw/test#1]
https://openuserjs.org/about/Userscript-Beginners-HOWTO#what-is-a-user-script-

... in short... use `git mv test.js test.user.js` with your local repo and push it to GH.

OUJS Admin

Ref:
* OpenUserJS/OpenUserJS.org#1762

---

Btw I'm noticing you have the same issue on your other repositories as well. Modify the file name accordingly for each of the Userscripts affected.

**Comment by HaleShaw** [comment]
> https://openuserjs.org/about/Userscript-Beginners-HOWTO#what-is-a-user-script-
> 
> ... in short... use `git mv test.js test.user.js` with your local repo and push it to GH.
> 
> OUJS Admin
> 
> Ref:
> 
> * [OpenUserJS/OpenUserJS.org#1762](https://github.com/OpenUserJS/OpenUserJS.org/issues/1762)
> 
> Btw I'm noticing you have the same issue on your other repositories as well. Modify the file name accordingly for each of the Userscripts affected.

I saw that it can import all the `.user.js` and `.js` files, so I didn't change the file name.
Now I get it. Just the library script file is named by the `.js`.
Thanks.

**Comment by HaleShaw** [comment]
Hi @Martii ,
There's a new issue.
File: https://raw.githubusercontent.com/HaleShaw/TM-BeautifyJenkins/master/BeautifyJenkins.user.js
Do the URL in the match list must be reachable?
But the host is the internal web site in my company.
![image](https://user-images.githubusercontent.com/32861865/93568692-18e7ba00-f9c3-11ea-981c-ef0552f99b9d.png)

**Comment by Martii** [comment]
Give GitHub a chance to cache it. On file renames it takes a bit.

**Comment by HaleShaw** [comment]
> Give GitHub a chance to cache it. On file renames it takes a bit.

Ok. I will check it later. Thanks.

**Comment by Martii** [comment]
> Do the URL in the match list must be reachable?

Nope.

However ENOTFOUND is not a good thing... restarted the server and it's still doing it as you on your OUJS account. Not sure what *node*s error means for sure.

**Comment by Martii** [comment]
Ahhh I see now... the one thing that does have to exist is your `@icon` which points to https://gkeselfbilljenkins.jaas-gcp.cloud.sap.corp/static/7ce2b5b0/favicon.ico ... In the web browser address bar it also shows as "server not found".

**Comment by HaleShaw** [comment]
> Ahhh I see now... the one thing that does have to exist is your `@icon` which points to https://gkeselfbilljenkins.jaas-gcp.cloud.sap.corp/static/7ce2b5b0/favicon.ico because we check it ... In the web browser address bar it also shows as "server not found".

Ah. So I must use a reachable URL for the `@icon`? For a internal script it may be not a good thing.😂

**Comment by Martii** [comment]
> So do I have to use a reachable URL for the @icon?
Yup.

You could always use an image [data URI](https://en.wikipedia.org/wiki/Data_URI_scheme) instead.

**Comment by Martii** [comment]
Taking just your metadata block and doing it direct on the site... you also have an insecure `@contributionURL`.

**Comment by HaleShaw** [comment]
> > So do I have to use a reachable URL for the `@icon`?
> 
> Yup.
> 
> You could always use an image [data URI](https://www.wikipedia.org/wiki/Data_URI_scheme) instead.

I can convert it to base64. But it's too long. It doesn't look very pretty in the metadata.
If there's no other solution, that's all I can do.

Ahh. Or I could look for the same picture on the outside. But it's not a perfect solution.

**Comment by HaleShaw** [comment]
By the way, I don't think OpenUserJS need to check the URL in the script.🤣
Greasy Fork not.

**Comment by Martii** [comment]
> I don't think OpenUserJS need to check the URL in the script.

GF not wise... OUJS wise! :smile_cat:

**Comment by HaleShaw** [comment]
> > I don't think OpenUserJS need to check the URL in the script.
> 
> GF not wise... OUJS wise! 😸

👍

This forced me to change the URL of the icon.😂

Anyway, after I updated the URL, it has been imported successfully.
Thanks a lot.

**Comment by Martii** [comment]
Welcome.
